### ISSUE TITLE
AssertionError: Database version not found: v1.0-trainval

### ISSUE THREAD

**Issue by lyzxcb** [ramdrop/AutoPlace#3]
Hello, I installed conda ,python environment and downloaded the dataset, but it is running/ gene_ woDTR. SH times wrong.
AssertionError: Database version not found: v1.0-trainval
![FIMJHB5()0E _J65YJWGOEL](https://user-images.githubusercontent.com/61130387/159863484-2b2df265-b7c4-452b-ba46-db53c5f6655a.png)
![H{IQGOU59F0_AT0IUD_GZY8](https://user-images.githubusercontent.com/61130387/159865393-a2a21540-d08c-485c-ab6e-e3de075436ea.png)
![0 S1_4)GC{OD@75Q%{E1ARP](https://user-images.githubusercontent.com/61130387/159865408-6e0f0df7-e827-4bcd-b2d5-924d9be67e1e.png)

**Comment by ramdrop** [comment]
Hi, you may need to define your downloaded nuScenes dataset directory in [generic.py: line 29](https://github.com/ramdrop/AutoPlace/blob/main/preprocess/utils/generic.py#L29).

**Comment by lyzxcb** [comment]
Thanks!This problem has been solved, but it is running "/gene_woDTR.sh" There are still some problems, which shows that “cannot be found n008-2018-08-01-16-03-27-0400_RADAR_ BACK_ LEFT__1533153857956096.pcd”. I downloaded the "radar blobs" part of these datasets in the figure below and put it under the path related to date/nuscenes. I don't know which step is wrong
![数据集下载界面](https://user-images.githubusercontent.com/61130387/161481136-d8b38c53-3f8a-4158-a3e5-9c7e328b4dc1.png)
![找不到pcd_1](https://user-images.githubusercontent.com/61130387/161481451-7bdc954f-f2e9-47d0-9261-1dada4f5830a.png)
![找不到pcd_2](https://user-images.githubusercontent.com/61130387/161481704-cde6c983-bbc1-43b1-9993-4b3f13ccf394.png)

**Comment by ramdrop** [comment]
You need to download **the Test split**, which includes : 
<img width="1325" alt="WX20220404-090838@2x" src="https://user-images.githubusercontent.com/73425467/161501616-a3946a93-6511-4d10-85a2-090fcddb2b09.png">

**Comment by lyzxcb** [comment]
thank! I was confused and forgot it. However, at present, I put the.pcd file in test into the "/date" path, and there are still problems when running "/ gene_wodtr. Sh", prompting "valueerror: not enough values to unpack (expected 3, got 2)". I haven't modified the source code. Do I need to modify some parameters?
![not enough values to unpack](https://user-images.githubusercontent.com/61130387/161693011-38af2f13-ebf7-42fe-a31b-15a1e53283a1.png)

**Comment by ramdrop** [comment]
I double-checked and found this is due to a recent change of nuscenes-devkit API . I have updated the requirements.txt file, now you can fix this issue by updating your environment by `pip install -r requirements.txt` or `pip install nuscenes-devkit==1.1.1`.

**Comment by lyzxcb** [comment]
Hello, I re established a CONDA environment and re downloaded and ran your newly released "autoplace" and "environment setup". The same problem still occurred when running ". / gene_wodtr. Sh". “ValueError: not enough values to unpack (expected 3, got 2)”
![C964@@TZSLCZCNWIO%({){S](https://user-images.githubusercontent.com/61130387/161958273-7e3c3d74-8600-45e7-9e5f-b0e091831928.png)
。

**Comment by ramdrop** [comment]
Could you please show me your nuscene-devkit version by  running `pip show nuscenes-devkit`?

**Comment by lyzxcb** [comment]
Hello, I deleted the previously downloaded "nuscenes devkit" and downloaded "nuscenes devkit = = 1.1.1" by running "pip install - r requirements. txt"
![KG1U{YU3MVDNSF34WF2KC6R](https://user-images.githubusercontent.com/61130387/161965447-ee935bbf-c3e9-470d-9728-8cc6eef1f4f1.png)

**Comment by ramdrop** [comment]
Hi, sorry I realized this API is indeed my customized function. To solve this issue, please run `git pull` and then modify the specific nuscenes-devkit API as I did:
go to the nuscenes-devkit package directory (depends on which python you are using), and override the function `from_file_multisweep(...)` in `site-packages/nuscenes/utils/data_classes.py` with the function provided in `autoplace/nuscenes-devkit_override.py`.
BTW, it is still okay to use nuscenes-devkit==1.1.1.

**Comment by lyzxcb** [comment]
Thank you for your reply. According to your prompt, the data preprocessing has been completed. There are some problems during training. When I run "3: train spatial encoder + temporary encoder (se_te)", the error appears to be that the graphics memory of the graphics card is not enough. For this problem, I have two questions:
 1 Do I need to change my computer with higher configuration for training? 
2. Can I continue to use this machine for training without changing the computer? Is there any difference in effect?
![Screenshot from 2022-04-21 15-45-42](https://user-images.githubusercontent.com/61130387/164408408-5b32a600-b35d-4b64-8eb8-e176d125938f.png)

**Comment by ramdrop** [comment]
1. To reproduce the same paper results I think you may need to resort to a graphics card with larger memory (~34GB).
2. To reduce the memory requirements, you may need to reduce either spatial feature dimensions or temporal feature dimensions. (1) For reducing spatial feature dimensions,  you can override [the Maxpooling layer](https://github.com/ramdrop/AutoPlace/blob/fbf6467aa6a0abf6566321cf9f50d713f3b3e1a7/networks/autoplace.py#L64) with a larger kernel size or stride. (2) For reducing temporal feature dimensions, you can reduce the hidden size of [the LSTM layer](https://github.com/ramdrop/AutoPlace/blob/fbf6467aa6a0abf6566321cf9f50d713f3b3e1a7/networks/autoplace.py#L68). But neither cases will promise a similar/comparable performance as the original network.

**Comment by lyzxcb** [comment]
Hello, I ran four "train" commands，in the evaluation report, "modulenotfounderror: no module named 'autoplace. Logs_autoplace. Networks'", I'm sorry to bother you. I'm really not familiar with Python. Is the path I added wrong?
![Screenshot from 2022-04-25 14-30-13](https://user-images.githubusercontent.com/61130387/165032915-93b4160e-b233-4498-8c4c-e757537f73eb.png)
![Screenshot from 2022-04-25 14-34-41](https://user-images.githubusercontent.com/61130387/165033213-dc44d3ad-9432-43d2-9729-526046c6c282.png)
![Screenshot from 2022-04-25 14-37-50](https://user-images.githubusercontent.com/61130387/165033654-2cb73c9c-897d-4375-86cb-4faf788ae3a4.png)

**Comment by ramdrop** [comment]
Your `resume` path should narrow down to the checkpoint file directory, as shown in [resume_path.json](https://github.com/ramdrop/AutoPlace/blob/fbf6467aa6a0abf6566321cf9f50d713f3b3e1a7/postprocess/parse/resume_path.json).

BTW, it is a better practice to open a new issue for a new error.

**Comment by Lancer-Archer-Caster** [comment]
> 您需要下载**测试拆分**，其中包括： <img alt="WX20220404-090838@2x" width="1325" src="https://user-images.githubusercontent.com/73425467/161501616-a3946a93-6511-4d10-85a2-090fcddb2b09.png">

你好，我下载了nuscenes Full datasetv1.0(除了mini),还是会显示缺少n015-2018-07-18-11-07-57+0800__LIDAR_TOP__1531883530449377.pcd.bin，请问哪里错了呢

![Image](https://github.com/user-attachments/assets/61520ee3-8cd8-4a5a-bdd6-abbf8a18b29b)
