### ISSUE TITLE
Hello, I have some questions about the ". Pickle" file in the folder.

### ISSUE THREAD

**Issue by lyzxcb** [ramdrop/AutoPlace#4]
Hello, I have some questions about the ". Pickle" file in the folder.
Question 1: Figure 1 is about the "features_test. Pickle" produced by "evaluate" after "se_dpr" training. I will open the line beginning with "gt": "1150、1151、2197、1148、1149、2196、2195、2194" respectively. The pictures under the corresponding "dateset / img" are shown in Figure 2. From the point cloud information shown in the figure, can it be understood that the upper row belongs to one scene and the lower row belongs to another scene? So why put them in an array in the ". Pickle" file?And they are not in positive order. For example, "2197" appears between "1151"and "1151".
Question 2: Figure 3 shows the data information of "se_te_results. Pickle". In the array of "preds", "1150,1277,4313" appear in "datebase" and "6113" appear in "test", but why do the numbers "37 "and "38 "not appear in "- test", "val", "train" and "- datebase"? What information do these numbers represent? Do they refer to the verified data set? Or other? I don't quite understand. And why do the middle of the data pass "..." Separated by ellipsis?
![5_4 图1](https://user-images.githubusercontent.com/61130387/166673824-14458d50-4f99-42c2-9663-25f7233a3435.png)
![5_4图2](https://user-images.githubusercontent.com/61130387/166673839-d54c514f-0e7d-49e0-9846-b539a9dea346.png)
![5_4图3](https://user-images.githubusercontent.com/61130387/166673853-1cab906e-b2f0-4ad8-85a0-c4f505800c06.png)
![5_4图4](https://user-images.githubusercontent.com/61130387/166674144-45c927ce-f05e-4c27-b7b4-ac96b1b2517e.png)

**Comment by ramdrop** [comment]
Hello,
For question 1: 

> From the point cloud information shown in the figure, can it be understood that the upper row belongs to one scene and the lower row belongs to another scene? 

Yes. Each array contains indices of samples within a certain radius of the corresponding query sample. This part of code shows how it is generated: https://github.com/ramdrop/autoplace/blob/fbf6467aa6a0abf6566321cf9f50d713f3b3e1a7/evaluate.py#L48.

For question 2:
The raw data provided by nuScenes is organized scene by scene, and I processed them sample by sample whthin each scene and generate processed samples. The generated samples are named by the order they are processed, so the indices/numbers are nothing more than labels. 

> In the array of "preds", "1150,1277,4313" appear in "datebase" and "6113" appear in "test", but why do the numbers "37 "and "38 "not appear in "- test", "val", "train" and "- datebase"? 

I partition the generated samples mostly based on when they were collected, for details of my partition stragety, please refer to https://github.com/ramdrop/autoplace/blob/fbf6467aa6a0abf6566321cf9f50d713f3b3e1a7/preprocess/split.py.

> And why do the middle of the data pass "..." Separated by ellipsis?

I believe this has something to do with python.
