### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by ZhouZijie77** [ramdrop/AutoPlace#5]
Hello, thank you for sharing your code. But I don't quite understand why you didn't use all samples to generate the database?

**Comment by ramdrop** [comment]
Hello, we are creating the database in a style that mimics practical use cases, which requires it to be "outdated". That is why we are creating the database from the first 105 days. Besides, uneven geometric distribution of samples may induce biases when evaluating a place recognition pipeline, so we are keeping each sample in the dataset 1 meter apart from each other.

**Comment by ZhouZijie77** [comment]
Thank you!
