### ISSUE TITLE
Does this method work with 3d radar point clouds with height info?

### ISSUE THREAD

**Issue by JzHuai0108** [ramdrop/AutoPlace#7]
Dear Sir,

The paper experiments used radar data from nuScenes. 
What is your opinion on using your method for 4D radar point clouds?
These point clouds have height info and often a 120 deg Horizontal FOV and 30 deg vertical FOV.

Thanks,

**Comment by ramdrop** [comment]
Hello, AutoPlace is primarily designed for 3D (XY+V) radar points clouds, the following factors should be considered when it is applied to 4D (XYZ+V) radar points:

1.  Feature extractor: a 3D CNN backbone might be needed.
2. Dynamic points removal: build a 3D mathematical relations.
3. RCSHR might be adopted as it is.

**Comment by JzHuai0108** [comment]
After brief reading of autoplace paper, I agree with your thoughts.
Thank you for the comments.
